security:
    encoders:
        AppBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    providers:
        main:
            entity: { class: AppBundle:User }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: .*
            form_login:
                provider: main
                login_path: app.security.login
                check_path: app.security.login
                use_referer: true
                username_parameter: login[username]
                password_parameter: login[password]
            remember_me:
                secret: "%secret%"
                domain: ~
                path:   /
                lifetime: 2592000
                remember_me_parameter: login[remember_me]
            logout:
                path:   app.security.logout
                target: app.default
                invalidate_session: false
            anonymous: true
            access_denied_url: app.security.denied
